### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PixelEyeStudios** [zabi94/Covens#10]
https://pastebin.com/Nm2ML5wj

Don't know if the link works, let me know if it doesn't.
Mods I have installed are:
JEI
Patchouli
Baubles
Covens 0.0.1.3
Better Animals
Better Animals Plus

**Comment by zabi94** [comment]
What forge version are you using?

**Comment by PixelEyeStudios** [comment]
1.12.2-14.23.5.2768

**Comment by PixelEyeStudios** [comment]
https://pastebin.com/Tz4YScg7
Same forge version
Mods:
Patchouli
Baubles
Covens
Openeye
(It also crashed without Openeye, I'm going to guess it's the forge version? what version is recommended?)

**Comment by zabi94** [comment]
You need forge latest, bot forge recommended. 
Forge latest is 14.23.5.2796

**Comment by PixelEyeStudios** [comment]
Ahhh I see, cheers
