### ISSUE TITLE
Another Crash

### ISSUE THREAD

**Issue by PixelEyeStudios** [zabi94/Covens#14]
I made myself a vampire and during the night, I set the time to 0. I died and clicked respawn and the screen went light blue and then I crashed
https://pastebin.com/sUTRrVwa

**Comment by zabi94** [comment]
This is weird. You managed to somehow place an item in the world as a block, but set the block back to air immediately... 
Easy fix, but curious behaviour, I wouldn't know how to reproduce this tbh
