### ISSUE TITLE
[1.12] Crash with Buildcraft

### ISSUE THREAD

**Issue by MasterEnderman** [zabi94/Covens#4]
Tested the new Version of Buildcraft with Covens and it crashes on Game start.

Reported it to the Buildcraft Dev Team before: https://github.com/BuildCraft/BuildCraft/issues/3876
They think the problem is how you're handeling oredict wildcard metadata.

Covens: 0.1.29
Forge: 14.23.1.2556
Buildcraft: 7.99.12
Crashreport: https://pastebin.com/UjEAWS8h

**Comment by zabi94** [comment]
Thanks for the report, fixing asap

**Comment by MasterEnderman** [comment]
thanks for the quick response.

**Comment by zabi94** [comment]
I didn't mean to close this, I'll wait until the next public update is out

**Comment by MokahTGS** [comment]
My crash log: https://pastebin.com/w1SpTRbm

any idea when this fix will get released?

**Comment by zabi94** [comment]
Never, actually. Covens is no longer being maintained as "Covens" but joined with witchworks into a new mod, bewitchment
