### ISSUE TITLE
[Suggestion] Familiars set by JSON file.

### ISSUE THREAD

**Issue by MokahTGS** [zabi94/Covens#5]
I was looking at your todo list and see that you will have familiars at some point and was wondering if you could set it up so that mod pack makers could define what familiars could be tamed.  I play with Animania and I would love a ferret familiar or hedgehog.

If the modpack maker could define the creature type, and maybe the ritual, and benefits in a JSON file it would open a whole slew of things you could do.

**Sorry...I hit enter at the subject line...sigh**

**Comment by zabi94** [comment]
Can you elaborate on how would it work?

**Comment by MokahTGS** [comment]
My thought would be instead of how Witchery used a transformation of one creature into another for a familiar, you could just do a binding ritual on any creature defined in the JSON, maybe even with different ritual requirements per creature...so tougher or cooler creatures would take harder to acquire materials.

**Comment by zabi94** [comment]
I can see if that's doable, but that sounds incredibly prone to bugs and extremely unflexible because of how I'll implement familiars
