### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Zygus42** [zabi94/Covens#6]
covens-0.1.29-dev
Baubles-1.12-1.5.1
forge-1.12.2-14.23.1.2556-installer-win

No other mods at all, and it crashes as soon as you start up minecraft.
[crash-2017-12-03_12.43.25-client.txt](https://github.com/zabi94/Covens/files/1524504/crash-2017-12-03_12.43.25-client.txt)

**Comment by zabi94** [comment]
Same setup freshly installed, runs just fine. 
- Where did you download the mods from? 
- Does it happen everytime you launch or just this single time? 
- Can you send me a [Pastebin](http://pastebin.com) of your instance/log/fml-client-latest.log file?

**Comment by Zygus42** [comment]
curseforge
Every time.

I reloaded the files from curseforge and it works fine now.  The old files still don't work.  Must have had some download corruption, although they look identical.
