### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by DragonOfStendarr** [zabi94/Covens#7]
My game (tested with only the mod and Baubles) crashes after a few sec loading in.. (covens-0.1.32-dev-branch2-patron)

**Comment by zabi94** [comment]
I see you're a new patron, thank you! That is not a fullscreen problem,
it's just that you are not registered to the beta testers list yet!

Il 22 dic 2017 22:34, "DragonOfStendarr" <notifications@github.com> ha
scritto:
