### ISSUE TITLE
reprint and translate

### ISSUE THREAD

**Issue by YangYangJun** [zabi94/Covens#8]
Excuse me，
Can I reprint your mod at the mcbbs forum in China, or can I translate your mod into Chinese?
Forum URL：http://www.mcbbs.net/portal.php

**Comment by zabi94** [comment]
No, the reason is that the mod is no longer being developed, but was joined with another mod into Bewitchment. You can join our [Discord server](http://discord.gg/Wj9PVEA) to keep up with development, if it is available in your country.

**Comment by YangYangJun** [comment]
Well, I know, but I can not join your server, I am just a junior high school, I just want more people to understand the mod, but since it has stopped development, we can only give up. But thank you for your invitation.

**Comment by zabi94** [comment]
I will write here when bewitchment will have a release available, so you can share it on mcbbs

**Comment by YangYangJun** [comment]
ok,thanks.
